require: rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/20141122230841_create_sites.rb'
    - 'db/migrate/20150926172242_create_delayed_jobs.rb'

Rails:
  Enabled: true

Rails/OutputSafety:
  Exclude:
    - 'app/views/layouts/_footer.html.haml*'
    - 'app/views/layouts/pages/_right_sidebar.html.haml*'
    - 'app/views/layouts/pages/_small_right_sidebar.html.haml*'
    - 'app/views/pages/_form.html.haml*'
    - 'app/views/pages/show.html.haml*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
