require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'puppet/**/*'
    - 'vendor/bundle/**/*'

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/20141122230841_create_sites.rb'
    - 'db/migrate/20150926172242_create_delayed_jobs.rb'

Rails:
  Enabled: true

RSpec/DescribeClass:
  Exclude:
    - 'spec/support/**/*'
    - 'spec/tasks/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
