require: rubocop-rspec

AllCops:
  RunRailsCops: true
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'puppet/**/*'
    - 'vendor/bundle/**/*'

HasAndBelongsToMany:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/20141122230841_add_sites.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/20141122230841_add_sites.rb'
    - 'db/migrate/20141123002911_add_pages.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/*'

Style/Documentation:
  Enabled: false
