require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/schema.rb'
    - 'puppet/**/*'
    - 'vendor/bundle/**/*'

Lint/HandleExceptions:
  Exclude:
    - 'bin/rails'
    - 'bin/rake'
    - 'bin/rspec'

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/20141122230841_create_sites.rb'
    - 'db/migrate/20150926172242_create_delayed_jobs.rb'

Rails:
  Enabled: true

RSpec/DescribeClass:
  Exclude:
    - 'spec/tasks/*_spec.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
