require: rubocop-rspec

AllCops:
  RunRailsCops: true
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'

HasAndBelongsToMany:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/*'

Style/Blocks:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Style/SpaceBeforeBlockBraces:
  Exclude:
    - 'spec/**/*'

Style/SpaceInsideBlockBraces:
  Exclude:
    - 'spec/**/*'
