---
include:
  - '**/*.rb'
exclude:
  - coverage/**/*
  - db/migrate/*_squash_migrations.rb
  - db/schema.rb
  - log/**/*
  - node_modules/**/*
  - public/**/*
  - spec/**/*
  - tmp/**/*
  - vendor/**/*
require:
  - rails
domains: []
reporters:
  - rubocop
plugins:
  - runtime
require_paths: []
max_files: 5000
