dist: trusty

sudo: false

branches:
  only: master

cache:
  bundler: true

git:
  depth: 3

addons:
  apt:
    packages:
      - libqt5webkit5-dev
      - qt5-default
  postgresql: "9.6"

services:
  - postgresql

env:
  - DATABASE_HOST=localhost TEST_COMMAND=./bin/quality
  - DATABASE_HOST=localhost TEST_COMMAND=./bin/setup
  - DATABASE_HOST=localhost TEST_COMMAND=./bin/test

script: $TEST_COMMAND && ./bin/changes
