branches:
  only: master

language: ruby

rvm: 2.1.5

services:
  - redis-server

bundler_args: --deployment --without development production

before_script:
  - psql -c 'create database cms_development;' -U postgres
  - psql -c 'create database cms_test;' -U postgres
  - cp config/secrets.yml.travis config/secrets.yml
  - ./bin/bootstrap

script: ./bin/test
