dist: trusty

sudo: false

branches:
  only: master

cache:
  bundler: true

git:
  depth: 3

addons:
  chrome: stable
  postgresql: "9.6"

services:
  - postgresql

before_install:
  - gem install bundler # TODO: remove when working

env:
  - TEST_COMMAND=./bin/quality
  - TEST_COMMAND=./bin/setup
  - TEST_COMMAND=./bin/test

script: $TEST_COMMAND && ./bin/changes
