language: ruby

rvm: 2.1.2

services: couchdb

bundler_args: --deployment --without development production

before_script:
  - ./bin/spring status
  - ./bin/bootstrap
  - ./bin/spring status

script:
  - ./bin/spring status
  - ./bin/test
  - ./bin/spring status
