dist: trusty

sudo: false

branches:
  only: master

language: ruby

cache:
  bundler: true
  directories:
    - tmp/cache/assets

addons:
  apt:
    packages:
      - libqt5webkit5-dev
      - qt5-default

services:
  - postgresql

env:
  - SCRIPT='./bin/rails db:create db:schema:load && DISABLE_SPRING=true COVERAGE=on xvfb-run --auto-servernum ./bin/rspec --color --order random'
  - SCRIPT='./bin/compile'
  - SCRIPT='./bin/quality'
  - SCRIPT='./bin/rails db:create db:migrate && ./bin/annotate --show-foreign-keys --show-indexes'

script:
  - echo $SCRIPT
  - eval $SCRIPT

after_success:
  - git clean --force public/assets/.sprockets-manifest-*.json
  - git checkout public/assets/.sprockets-manifest-*.json
  - ./bin/changes
