sudo: required

dist: trusty

branches:
  only: master

language: ruby

cache: bundler

addons:
  apt:
    packages:
    - libqt5webkit5-dev
    - qt5-default

before_script: ./bin/setup

script:
  - ./bin/test
  - git clean --force public/assets/.sprockets-manifest-*.json
  - git checkout public/assets/.sprockets-manifest-*.json
  - ./bin/changes
