branches:
  only: master

language: ruby

rvm: 2.1.4

services: couchdb

bundler_args: --deployment --without development production

before_script:
  - ./bin/bootstrap
  - ./bin/spring stop

script: ./bin/test
