branches:
  only: master

cache:
  bundler: true
  directories:
    - node_modules

git:
  depth: 3

addons:
  chrome: stable
  postgresql: 9.6 # TODO - upgrade to 10 when Travis supports it

services:
  - postgresql

script: ./bin/setup && ./bin/test && ./bin/changes
