sudo: false

branches:
  only: master

language: ruby

cache: bundler

services:
  - redis-server

before_script:
  - cp config/secrets.yml.travis config/secrets.yml
  - ./bin/bootstrap

script:
  - ./bin/test
  - git checkout public/assets/manifest-*
  - ./bin/changes
