language: ruby

rvm: 2.0.0

services: couchdb

cache: bundler

bundler_args: --deployment --without development production

before_script:
  - ./bin/bootstrap
  - ./bin/rake assets:precompile

script: ./bin/test
