sudo: required

dist: trusty

branches:
  only: master

language: ruby

cache: bundler

services:
  - redis-server

before_install:
  - gem install bundler

before_script: ./bin/bootstrap

script:
  - ./bin/test
  - git clean --force public/assets/.sprockets-manifest-*.json
  - git checkout public/assets/.sprockets-manifest-*.json
  - ./bin/changes
