dist: trusty

sudo: required

branches:
  only: master

language: ruby

cache:
  bundler: true
  directories:
    - tmp/cache/assets

addons:
  apt:
    packages:
      - libqt5webkit5-dev
      - qt5-default

services:
  - postgresql

script:
  - ./bin/test
  - ./bin/annotate --show-foreign-keys --show-indexes
  - git clean --force public/assets/.sprockets-manifest-*.json
  - git checkout public/assets/.sprockets-manifest-*.json
  - ./bin/changes
