dist: trusty

sudo: false

branches:
  only: master

language: ruby

cache: bundler

services:
  - postgresql

before_script:
  - qmake --version
  - ./bin/setup

script:
  - ./bin/test
  - git clean --force public/assets/.sprockets-manifest-*.json
  - git checkout public/assets/.sprockets-manifest-*.json
  - ./bin/changes
