dist: trusty

sudo: false

branches:
  only: master

cache:
  bundler: true
  directories:
    - node_modules

git:
  depth: 3

addons:
  chrome: stable
  postgresql: "9.6"

services:
  - postgresql

script: ./bin/setup && ./bin/test && ./bin/changes
