sudo: false

branches:
  only: master

language: ruby

cache: bundler

services:
  - redis-server

before_script: ./bin/bootstrap

script:
  - ./bin/test
  - git clean --force public/assets/
  - git checkout public/assets/
  - ./bin/changes
