dist: trusty

branches:
  only: master

cache: bundler

services:
  - redis-server

before_install:
  - sudo apt-get update --assume-yes
  - sudo apt-get install --assume-yes libqt5webkit5-dev qt5-default xvfb

before_script: ./bin/bootstrap

script:
  - ./bin/test
  - git clean --force public/assets/.sprockets-manifest-*.json
  - git checkout public/assets/.sprockets-manifest-*.json
  - ./bin/changes
