sudo: false

branches:
  only: master

language: ruby

rvm: 2.2.0

cache: bundler

services:
  - redis-server

bundler_args: --deployment --without development production

before_script:
  - cp config/secrets.yml.travis config/secrets.yml
  - ./bin/bootstrap

script: ./bin/test
