branches:
  only: master

language: ruby

rvm: 2.1.5

services:
  - couchdb
  - redis-server

bundler_args: --deployment --without development production

before_script:
  - ./bin/bootstrap
  - ./bin/spring stop

script: ./bin/test
