version: "3"

services:
  db:
    environment:
      - POSTGRES_USER=postgres
    image: "postgres:9.6"
    ports:
      - "5432:5432"
    volumes:
      - "db:/var/lib/postgresql/data"

  email:
    image: "schickling/mailcatcher"
    ports:
      - "1025:1025"
      - "1080:1080"

  swagger:
    environment:
      - "API_URL=http://localhost:3000/api/swagger"
    image: "swaggerapi/swagger-ui"
    ports:
      - "8080:8080"

volumes:
  db:
