---
AWSTemplateFormatVersion: "2010-09-09"

Description: "obduk-cms app"

Outputs:
  AssetHost:
    Description: "Value for ASSET_HOST"
    Value: !Sub "https://${CloudFront.DomainName}"
  AwsAccessKeyId:
    Description: "Value for AWS_ACCESS_KEY_ID"
    Value: !Ref IAMUserAccessKey
  AwsRegion:
    Description: "Value for AWS_REGION"
    Value: !Ref "AWS::Region"
  AwsS3Bucket:
    Description: "Value for AWS_S3_BUCKET"
    Value: !Ref S3Bucket
  AwsSecretAccessKey:
    Description: "Value for AWS_SECRET_ACCESS_KEY"
    Value: !GetAtt IAMUserAccessKey.SecretAccessKey

Resources:
  CloudFront:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        CacheBehaviors:
          - Compress: true
            ForwardedValues:
              QueryString: false
            PathPattern: /css/*
            TargetOriginId: App
            ViewerProtocolPolicy: redirect-to-https
          - Compress: true
            ForwardedValues:
              QueryString: false
            PathPattern: /packs/*
            TargetOriginId: App
            ViewerProtocolPolicy: redirect-to-https
        Comment: !Ref "AWS::StackName"
        DefaultCacheBehavior:
          Compress: true
          ForwardedValues:
            QueryString: false
          TargetOriginId: S3
          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: true
        Logging:
          Bucket: !GetAtt S3LogsBucket.DomainName
          Prefix: !Sub "AWSLogs/${AWS::AccountId}/cloudfront/${AWS::StackName}/"
        Origins:
          - DomainName: !GetAtt S3Bucket.DomainName
            Id: S3
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}"
          - CustomOriginConfig:
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2
                - TLSv1.1
                - TLSv1
            DomainName: !Sub "${AWS::StackName}.herokuapp.com"
            Id: App

  CloudFrontOriginAccessIdentity:
    Type: "AWS::CloudFront::CloudFrontOriginAccessIdentity"
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref "AWS::StackName"

  IAMUser:
    Type: "AWS::IAM::User"
    Properties:
      UserName: !Ref "AWS::StackName"
      Policies:
        - PolicyName: access-s3-bucket
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "s3:ListBucket"
                Resource: !GetAtt S3Bucket.Arn
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:GetObjectAcl"
                  - "s3:PutObject"
                  - "s3:PutObjectAcl"
                  - "s3:DeleteObject"
                Resource: !Sub "${S3Bucket.Arn}/*"
        - PolicyName: send-ses-email
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "ses:SendRawEmail"
                Resource: "*"

  IAMUserAccessKey:
    Type: "AWS::IAM::AccessKey"
    Properties:
      UserName: !Ref IAMUser

  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Ref "AWS::StackName"
      LifecycleConfiguration:
        Rules:
          - Id: delete-incomplete-multipart-uploads
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
            Status: Enabled
          - Id: delete-old-versions
            NoncurrentVersionExpirationInDays: 30
            Status: Enabled
      LoggingConfiguration:
        DestinationBucketName: !Ref S3LogsBucket
        LogFilePrefix: !Sub "AWSLogs/${AWS::AccountId}/s3/${AWS::StackName}/"
      VersioningConfiguration:
        Status: Enabled

  S3BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginAccessIdentity}"
            Action: "s3:GetObject"
            Resource: !Sub "${S3Bucket.Arn}/*"

  S3LogsBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: LogDeliveryWrite
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Sub "${AWS::StackName}-logs"
      LifecycleConfiguration:
        Rules:
          - Id: delete-incomplete-multipart-uploads
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
            Status: Enabled
          - Id: delete-old-files
            ExpirationInDays: 30
            Status: Enabled
          - Id: delete-old-versions
            NoncurrentVersionExpirationInDays: 30
            Status: Enabled
      VersioningConfiguration:
        Status: Enabled
