version: 2

jobs:
  build:
    docker:
       - image: circleci/ruby:2.5.3-node-browsers
       - image: circleci/postgres:10-alpine-ram

    steps:
      - checkout

      - restore_cache:
          keys:
            - tmp-{{ .Branch }}-{{ .Revision }}
            - tmp-{{ .Branch }}-
            - tmp-

      - restore_cache:
          keys:
            - bundle-{{ checksum "Gemfile.lock" }}
            - bundle-

      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
            - yarn-

      - run:
          command: ./bin/setup

      - save_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run:
          command: ./bin/compile
          environment:
            RAILS_ENV: test

      - run:
          command: ./bin/test

      - run:
          command: ./bin/quality

      - save_cache:
          key: tmp-{{ .Branch }}-{{ .Revision }}
          paths:
            - public/packs-test
            - tmp/cache/bootsnap-compile-cache
            - tmp/cache/bootsnap-load-path-cache
            - tmp/cache/webpacker
            - tmp/parallel_runtime_rspec.log

      - run:
          command: ./bin/changes

      - store_test_results:
          path: tmp/test_results

      - store_artifacts:
          path: coverage
          destination: coverage
