version: 2

terraform_defaults: &terraform_defaults
  docker:
    - image: hashicorp/terraform:light

  environment:
    TF_IN_AUTOMATION: "true"
    TF_INPUT: "false"

terraform_checkout: &terraform_checkout
  checkout:
    path: ~/project

terraform_init: &terraform_init
  run:
    command: terraform init

terraform_test: &terraform_test
  steps:
    - *terraform_checkout
    - run:
        command: terraform fmt -check=true

terraform_plan: &terraform_plan
  steps:
    - *terraform_checkout
    - *terraform_init
    - run:
        command: terraform plan -lock=false

terraform_deploy: &terraform_deploy
  steps:
    - *terraform_checkout
    - *terraform_init
    - run:
        command: terraform apply -auto-approve

jobs:
  test_ruby:
    docker:
      - image: circleci/ruby:2.5.3-node-browsers
      - image: circleci/postgres:10-alpine-ram

    steps:
      - checkout

      - restore_cache:
          keys:
            - bootsnap-{{ checksum ".ruby-version" }}-{{ .Environment.CIRCLE_PREVIOUS_BUILD_NUM }}

      - restore_cache:
          keys:
            - bundle-{{ checksum ".ruby-version" }}-{{ checksum "Gemfile.lock" }}
            - bundle-{{ checksum ".ruby-version" }}-

      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
            - yarn-

      - run:
          command: ./bin/setup

      - save_cache:
          key: bundle-{{ checksum ".ruby-version" }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - restore_cache:
          keys:
            - webpacker-{{ .Environment.CIRCLE_PREVIOUS_BUILD_NUM }}

      - run:
          command: ./bin/compile
          environment:
            RAILS_ENV: test

      - save_cache:
          key: webpacker-{{ .Environment.CIRCLE_BUILD_NUM }}
          paths:
            - public/packs-test
            - tmp/cache/webpacker

      - restore_cache:
          keys:
            - parallel-{{ .Environment.CIRCLE_PREVIOUS_BUILD_NUM }}

      - run:
          command: ./bin/test

      - save_cache:
          key: parallel-{{ .Environment.CIRCLE_BUILD_NUM }}
          paths:
            - tmp/parallel_runtime_rspec.log

      - run:
          command: ./bin/quality

      - save_cache:
          key: bootsnap-{{ checksum ".ruby-version" }}-{{ .Environment.CIRCLE_BUILD_NUM }}
          paths:
            - tmp/cache/bootsnap-compile-cache
            - tmp/cache/bootsnap-load-path-cache

      - run:
          name: Changes
          command: |
            if [[ $(git status --porcelain) != '' ]]
            then
              git status
              exit 1
            fi

      - store_test_results:
          path: tmp/test_results

      - store_artifacts:
          path: coverage
          destination: coverage

  test_terraform_app_environment:
    <<: *terraform_defaults
    <<: *terraform_test
    working_directory: ~/project/terraform/app_environment

  plan_terraform_app_environment_staging:
    <<: *terraform_defaults
    <<: *terraform_plan
    working_directory: ~/project/terraform/app_environment

  deploy_terraform_app_environment_staging:
    <<: *terraform_defaults
    <<: *terraform_deploy
    working_directory: ~/project/terraform/app_environment

only_master: &only_master
  filters:
    branches:
      only:
        - master

workflows:
  version: 2
  commit:
    jobs:
      - test_ruby

      - test_terraform_app_environment

      - plan_terraform_app_environment_staging:
          context: cms_terraform_app_environment_staging
          requires:
            - test_terraform_app_environment

      - deploy_terraform_app_environment_staging:
          <<: *only_master
          context: cms_terraform_app_environment_staging
          requires:
            - test_ruby
            - plan_terraform_app_environment_staging
