version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3-node-browsers
      - image: circleci/postgres:10-alpine-ram

    steps:
      - checkout

      - restore_cache:
          keys:
            - bootsnap-{{ checksum ".ruby-version" }}-{{ .Environment.CIRCLE_PREVIOUS_BUILD_NUM }}

      - restore_cache:
          keys:
            - bundle-{{ checksum ".ruby-version" }}-{{ checksum "Gemfile.lock" }}
            - bundle-{{ checksum ".ruby-version" }}-

      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
            - yarn-

      - run:
          command: ./bin/setup

      - save_cache:
          key: bundle-{{ checksum ".ruby-version" }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - restore_cache:
          keys:
            - webpacker-{{ .Environment.CIRCLE_PREVIOUS_BUILD_NUM }}

      - run:
          command: ./bin/compile
          environment:
            RAILS_ENV: test

      - save_cache:
          key: webpacker-{{ .Environment.CIRCLE_BUILD_NUM }}
          paths:
            - public/packs-test
            - tmp/cache/webpacker

      - restore_cache:
          keys:
            - parallel-{{ .Environment.CIRCLE_PREVIOUS_BUILD_NUM }}

      - run:
          command: ./bin/test

      - save_cache:
          key: parallel-{{ .Environment.CIRCLE_BUILD_NUM }}
          paths:
            - tmp/parallel_runtime_rspec.log

      - run:
          command: ./bin/quality

      - save_cache:
          key: bootsnap-{{ checksum ".ruby-version" }}-{{ .Environment.CIRCLE_BUILD_NUM }}
          paths:
            - tmp/cache/bootsnap-compile-cache
            - tmp/cache/bootsnap-load-path-cache

      - run:
          command: ./bin/changes

      - store_test_results:
          path: tmp/test_results

      - store_artifacts:
          path: coverage
          destination: coverage
