development:
  database: <%= [ENV['COUCHDB_URL'], ENV['COUCHDB_NAME']].compact.join('/') %>

test:
  database: <%= [ENV['COUCHDB_URL'], ENV['COUCHDB_NAME']].compact.join('/') %>

production:
  database: <%= [ENV['CLOUDANT_URL'], ENV['COUCHDB_NAME']].compact.join('/') %>
