defaults: &defaults
  database: <%= [(ENV['COUCHDB_URL'] || ENV['CLOUDANT_URL']), ENV['COUCHDB_NAME']].compact.join('/') %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
