development:
  database: <%= ENV['COUCHDB_URL'] %>

development_backup:
  database: <%= ENV['COUCHDB_BACKUP_URL'] %>

test:
  database: <%= ENV['COUCHDB_URL'] %>

test_backup:
  database: <%= ENV['COUCHDB_BACKUP_URL'] %>

production:
  database: <%= if ENV['CLOUDANT_URL'] then ENV['CLOUDANT_URL'] + '/production_cms' end %>

production_backup:
  database: <%= ENV['COUCHDB_BACKUP_URL'] %>
