default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['MAX_THREADS'] || 5 %>
  url: <%= Rails.application.secrets.database_url %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
