development:
  database_url: <%= ENV['DATABASE_URL'] || 'postgres://cms_development:password@localhost/cms_development' %>
  dev_assets: true
  redis_server: 'redis://127.0.0.1:6379/0/cms-development'
  secret_key_base: 'xxxxxxxxxxxxxxxxxxxx'
  smtp_address: 'localhost'
  smtp_port: 1025
  timeout: 10
  uploads_storage: 'file'
  uploads_store_dir: 'uploads'

test:
  database_url: <%= ENV['DATABASE_URL'] || 'postgres://cms_test:password@localhost/cms_test' %>
  loaderio_token: 'loaderio-12345'
  redis_server: 'redis://127.0.0.1:6379/0/cms-test'
  secret_key_base: 'xxxxxxxxxxxxxxxxxxxx'
  uploads_storage: 'file'
  uploads_store_dir: 'test_uploads'

production:
  asset_host: <%= ENV['ASSET_HOST'] %>
  aws_bucket: <%= ENV['AWS_BUCKET'] %>
  aws_host: <%= ENV['AWS_HOST'] %>
  aws_key: <%= ENV['AWS_KEY'] %>
  aws_region: <%= ENV['AWS_REGION'] %>
  aws_secret: <%= ENV['AWS_SECRET'] %>
  database_url: <%= ENV['DATABASE_URL'] %>
  loaderio_token: <%= ENV['LOADERIO_TOKEN'] %>
  new_relic_app_name: <%= ENV['NEW_RELIC_APP_NAME'] %>
  new_relic_license_key: <%= ENV['NEW_RELIC_LICENSE_KEY'] %>
  redis_server: <%= ENV['REDIS_SERVER'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  sentry_dsn: <%= ENV['SENTRY_DSN'] %>
  smtp_address: <%= ENV['SMTP_ADDRESS'] %>
  smtp_password: <%= ENV['SMTP_PASSWORD'] %>
  smtp_port: <%= ENV['SMTP_PORT'] || 587 %>
  smtp_username: <%= ENV['SMTP_USERNAME'] %>
  uploads_storage: <%= ENV['UPLOADS_STORAGE'] %>
