development:
  database_url: 'postgres://postgres@localhost/cms_development'
  dev_assets: true
  email_from_address: 'noreply@example.com'
  email_provider: 'letter_opener'
  host: 'cms.dev'
  redis_url: 'redis://127.0.0.1:6379/0/cms-development'
  secret_key_base: 'xxxxxxxxxxxxxxxxxxxx'
  sysadmin_email: 'test@example.com'
  timeout: '10'

test:
  aws_region: 'eu-east-1'
  database_url: 'postgres://postgres@localhost/cms_test'
  email_from_address: 'noreply@example.com'
  host: 'cms.dev'
  iam_key: 'xxxxxxxxxxxxxxxxxxxx'
  iam_secret: 'xxxxxxxxxxxxxxxxxxxx'
  redis_url: 'redis://127.0.0.1:6379/0/cms-test'
  s3_bucket: 'obduk-cms-test'
  s3_host: 'https://obduk-cms-test.s3-eu-west-1.amazonaws.com'
  secret_key_base: 'xxxxxxxxxxxxxxxxxxxx'
  sysadmin_email: 'test@example.com'
  timeout: '2'

production:
  asset_host: <%= ENV['ASSET_HOST'] %>
  aws_region: <%= ENV['AWS_REGION'] %>
  database_url: <%= ENV['DATABASE_URL'] %>
  email_from_address: <%= ENV['EMAIL_FROM_ADDRESS'] %>
  email_provider: <%= ENV['EMAIL_PROVIDER'] || 'sendgrid' %>
  host: <%= ENV['HOST'] || ("#{ENV['HEROKU_APP_NAME']}.herokuapp.com" if ENV['HEROKU_APP_NAME']) %>
  iam_key: <%= ENV['IAM_KEY'] %>
  iam_secret: <%= ENV['IAM_SECRET'] %>
  new_relic_app_name: <%= ENV['HEROKU_APP_NAME'] %>
  new_relic_license_key: <%= ENV['NEW_RELIC_LICENSE_KEY'] %>
  redis_url: <%= ENV['REDIS_URL'] %>
  s3_bucket: <%= ENV['S3_BUCKET'] %>
  s3_host: <%= ENV['S3_HOST'] || "https://#{ENV['S3_BUCKET']}.s3-#{ENV['AWS_REGION']}.amazonaws.com" %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  sysadmin_email: <%= ENV['SYSADMIN_EMAIL'] %>
  timeout: <%= ENV['TIMEOUT'] || '5' %>
