development:
  admin_email: 'test@example.com'
  database_url: 'postgres://postgres@localhost/cms_development'
  dev_assets: true
  host: 'cms.dev'
  redis_url: 'redis://127.0.0.1:6379/0/cms-development'
  secret_key_base: 'xxxxxxxxxxxxxxxxxxxx'
  smtp_address: 'localhost'
  smtp_port: '1025'
  timeout: '10'

test:
  admin_email: 'test@example.com'
  database_url: 'postgres://postgres@localhost/cms_test'
  host: 'cms.dev'
  iam_key: 'xxxxxxxxxxxxxxxxxxxx'
  iam_secret: 'xxxxxxxxxxxxxxxxxxxx'
  redis_url: 'redis://127.0.0.1:6379/0/cms-test'
  s3_bucket: 'obduk-cms-test'
  s3_host: 'https://obduk-cms-test.s3-eu-west-1.amazonaws.com'
  s3_region: 'eu-west-1'
  secret_key_base: 'xxxxxxxxxxxxxxxxxxxx'
  timeout: '2'

production:
  admin_email: <%= ENV['ADMIN_EMAIL'] %>
  asset_host: <%= ENV['ASSET_HOST'] %>
  database_url: <%= ENV['DATABASE_URL'] %>
  host: <%= ENV['HOST'] || ("#{ENV['HEROKU_APP_NAME']}.herokuapp.com" if ENV['HEROKU_APP_NAME']) %>
  iam_key: <%= ENV['IAM_KEY'] %>
  iam_secret: <%= ENV['IAM_SECRET'] %>
  new_relic_app_name: <%= ENV['NEW_RELIC_APP_NAME'] || ENV['HEROKU_APP_NAME'] %>
  new_relic_license_key: <%= ENV['NEW_RELIC_LICENSE_KEY'] %>
  redis_url: <%= ENV['REDIS_URL'] %>
  s3_bucket: <%= ENV['S3_BUCKET'] %>
  s3_host: <%= ENV['S3_HOST'] %>
  s3_region: <%= ENV['S3_REGION'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  smtp_address: <%= ENV['SMTP_ADDRESS'] || 'smtp.sendgrid.net' %>
  smtp_password: <%= ENV['SMTP_PASSWORD'] || ENV['SENDGRID_PASSWORD'] %>
  smtp_port: <%= ENV['SMTP_PORT'] || '587' %>
  smtp_username: <%= ENV['SMTP_USERNAME'] || ENV['SENDGRID_USERNAME'] %>
  timeout: <%= ENV['TIMEOUT'] || '5' %>
