development:
  database_url: <%= ENV['DATABASE_URL'] || 'postgres://cms_development:password@localhost/cms_development' %>
  dev_assets: true
  redis_url: 'redis://127.0.0.1:6379/0/cms-development'
  secret_key_base: 'xxxxxxxxxxxxxxxxxxxx'
  smtp_address: 'localhost'
  smtp_port: 1025
  timeout: 10
  uploads_store_dir: 'uploads'

test:
  database_url: <%= ENV['DATABASE_URL'] || 'postgres://cms_test:password@localhost/cms_test' %>
  loaderio_token: 'loaderio-12345'
  redis_url: 'redis://127.0.0.1:6379/0/cms-test'
  secret_key_base: 'xxxxxxxxxxxxxxxxxxxx'
  uploads_store_dir: 'test_uploads'

production:
  asset_host: <%= ENV['ASSET_HOST'] %>
  database_url: <%= ENV['DATABASE_URL'] %>
  loaderio_token: <%= ENV['LOADERIO_TOKEN'] %>
  new_relic_app_name: <%= ENV['NEW_RELIC_APP_NAME'] %>
  new_relic_license_key: <%= ENV['NEW_RELIC_LICENSE_KEY'] %>
  redis_url: <%= ENV['REDIS_URL'] %>
  s3_bucket: <%= ENV['S3_BUCKET'] %>
  s3_host: <%= ENV['S3_HOST'] %>
  s3_key: <%= ENV['S3_KEY'] %>
  s3_region: <%= ENV['S3_REGION'] %>
  s3_secret: <%= ENV['S3_SECRET'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  sentry_dsn: <%= ENV['SENTRY_DSN'] %>
  smtp_address: <%= ENV['SMTP_ADDRESS'] || 'smtp.sendgrid.net' %>
  smtp_password: <%= ENV['SMTP_PASSWORD'] || ENV['SENDGRID_PASSWORD'] %>
  smtp_port: <%= ENV['SMTP_PORT'] || 587 %>
  smtp_username: <%= ENV['SMTP_USERNAME'] || ENV['SENDGRID_USERNAME'] %>
