block_formats: 'Main Header=h2;Sub Header=h3;Paragraph=p'
browser_spellcheck: true
element_format: 'html'
entity_encoding: 'raw'
inline: true
menubar: false
plugins:
  - autolink
  - link
  - lists
  - paste
selector: '.editor'
toolbar: 'formatselect bold italic subscript superscript | bullist numlist | link'
