name: Automerge

on:
  workflow_run:
    workflows: ['Test']
    types:
      - completed

jobs:
  automerge:
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' &&
      github.actor == 'dependabot[bot]'

    runs-on: ubuntu-latest

    steps:
      - name: Print github context
        env:
          GITHUB_CONTEXT: ${{ output.workflow_run.pull_requests[0].number }}
        run: echo $GITHUB_CONTEXT

      - uses: actions/github-script@0.2.0
        with:
          github-token: ${{ github.token }}
          script: |
            github.pullRequests.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: github.event.workflow_run.pull_requests[0].number
            })
