name: Automerge

on:
  workflow_run:
    workflows: ['Test']
    types:
      - completed

jobs:
  automerge:
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' &&
      github.actor == 'dependabot[bot]'

    runs-on: ubuntu-latest

    env:
      PR_NUMBER1: ${{ github.event.number }}
      PR_NUMBER2: ${{ github.event.workflow_run.pull_request.number }}

    steps:
      - run: echo $PR_NUMBER1

      - run: echo $PR_NUMBER2

      - uses: actions/github-script@0.2.0
        with:
          github-token: ${{ github.token }}
          script: |
            github.pullRequests.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: github.event.workflow_run.pull_request.number
            })
