name: Deploy

on:
  workflow_run:
    workflows: ['Test']
    types:
      - completed

env:
  TF_VERSION: 0.14.10

jobs:
  deploy:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.ref == 'refs/heads/master'

    strategy:
      max-parallel: 1

      matrix:
        tf_workspace: [staging, production, global]
        include:
          - tf_workspace: staging
            tf_dir: terraform/app_environment
          - tf_workspace: production
            tf_dir: terraform/app_environment
          - tf_workspace: global
            tf_dir: terraform/app_global

    env:
      WORKFLOW_RUN_EVENT: ${{ github.event.workflow_run.event }}
      TF_WORKSPACE: ${{ matrix.tf_workspace }}

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ matrix.tf_dir }}

    steps:
      - run: echo $WORKFLOW_RUN_EVENT

      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

      - run: terraform init

      - run: terraform apply -lock-timeout=30s

      - name: Run git diff
        run: if [[ $(git status --porcelain) != '' ]]; then git status; git diff; exit 1; fi
