name: Terraform Plan

on:
  workflow_run:
    workflows: ['Test']
    types:
      - completed

env:
  TF_VERSION: 0.14.8

jobs:
  terraform_plan:
    strategy:
      max-parallel: 1

      matrix:
        tf_workspace: [staging, production, global]
        include:
          - tf_workspace: staging
            tf_dir: terraform/app_environment
          - tf_workspace: production
            tf_dir: terraform/app_environment
          - tf_workspace: global
            tf_dir: terraform/app_global

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ matrix.tf_dir }}

    env:
      TF_WORKSPACE: ${{ matrix.tf_workspace }}

    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

      - run: terraform fmt -check -recursive

      - run: terraform init -lock=false

      - run: terraform plan -lock=false

      - name: Run git diff
        run: if [[ $(git status --porcelain) != '' ]]; then git status; git diff; exit 1; fi
