name: Test

on:
  push:
    branches: [main, master]
  pull_request:

env:
  NODE_VERSION: 14.16.0

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.11-alpine
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - uses: nanasess/setup-chromedriver@master

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache yarn
        uses: actions/cache@v1
        with:
          path: node_modules
          key: yarn-${{ hashFiles('.nvmrc') }}-${{ hashFiles('yarn.lock') }}
          restore-keys: yarn-${{ hashFiles('.nvmrc') }}-

      - run: ./bin/setup

      - run: RAILS_ENV=test ./bin/rails webpacker:compile

      - run: ./bin/test

      - run: ./bin/quality

      - name: Run git diff
        run: if [[ $(git status --porcelain) != '' ]]; then git status; git diff; exit 1; fi
